version: "2"
services:
  app:
    container_name: gamesareart
    restart: always
    build: .
    ports:
      - "3001:3001"
    links:
      - mongo
      - back-office
  mongo:
    container_name: mongo_db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  back-office:
    container_name: back-office
    restart: always
    build: 
      context: back-office
      dockerfile: Dockerfile
    ports:
      - 4201:4201
