version: "2"
services:
  server-api:
    container_name: server-api
    restart: always
    build:
      context: server-api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      WAIT_HOSTS: mongodb:27017
    depends_on: 
      - mongodb
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - .mongoBackup/data:/data/db
    ports:
      - "27017:27017"
  back-office:
    container_name: back-office
    restart: always
    build: 
      context: back-office
      dockerfile: Dockerfile
    ports:
      - 4201:4201
    depends_on:
      - server-api
    links:
      - server-api
  gamesareart:
      container_name: gamesareart
      restart: always
      build: 
        context: front-end
        dockerfile: Dockerfile
      ports:
        - 8080:8080
      depends_on:
        - server-api
      links:
        - server-api
