version: "2"
services:
  server-api:
    container_name: server-api
    restart: always
    build:
      context: server-api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    links:
      - mongo
  mongo:
    container_name: mongo_db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  back-office:
    container_name: back-office
    restart: always
    build: 
      context: back-office
      dockerfile: Dockerfile
    ports:
      - 4201:4201
    links:
      - server-api
